version: "3.8"

services:
  # config for reverse proxy
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - /etc/certs:/etc/certs

  # config for single user servers
  jupyter_server:
    build: 
      context: ./
      dockerfile: ./${SERVER_DOCKER_PATH}/Dockerfile
      args: 
        - SERVER_DOCKER_PATH=${SERVER_DOCKER_PATH}
        - HUB_VERSION=${JUPYTERHUB_VERSION}
        - ISLETS_VERSION=${ISLETS_VERSION}
    image: ${SERVER_IMAGE_NAME}:${ISLETS_VERSION}
    networks:
      - default
    command: echo

  # config for Hub
  jupyterhub:
    depends_on:
      - "reverse-proxy"
    build: 
      context: ./
      dockerfile: ./${HUB_DOCKER_PATH}/Dockerfile
      args:
        - HUB_DOCKER_PATH=${HUB_DOCKER_PATH}
        - HUB_VERSION=${JUPYTERHUB_VERSION}
    image: ${HUB_CONTAINER_NAME}:${ISLETS_VERSION}
    container_name: ${HUB_CONTAINER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock                # Give access to Docker socket.
      - jupyterhub_data:/data/:rw                                # Add a data partition for data storage.
    environment:                                                 # Env variables passed to the Hub process.
      - DOCKER_JUPYTER_CONTAINER=${SERVER_IMAGE_NAME}
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=${HUB_CONTAINER_NAME}
      - HOST
      - ISLETS_VERSION
    networks:
      - default
    labels:                                                       # Traefik configuration.
      - "traefik.enable=true"                                     # enable Traefik for this service
      - "traefik.frontend.rule=Host:${HOST}"                      # apply rule for frontend
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_default"  # use internal docker network
      - "traefik.http.routers.jupyterhub.rule=Host(`${HOST}`)"    # apply routing through traefik
  
volumes:
  jupyterhub_data:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_default
